"""Token-based Markdown text extraction for Microsoft Learn source articles.

Text is read from markdown-it inline tokens, so escapes (``\\*``), entities, emphasis, code
spans, and links are interpreted by the Markdown parser rather than by stripping characters from
raw source with regular expressions.
"""

from __future__ import annotations

import posixpath
import re
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from typing import Any

from markdown_it import MarkdownIt
from markdown_it.token import Token

from d365_pqu.errors import ParserError

LEARN_LOCALE_BASE = "https://learn.microsoft.com/en-us/"
DYNAMICS_BASE = f"{LEARN_LOCALE_BASE}dynamics365/"
ARTICLES_ROOT = "articles/"
CALLOUT_KINDS = ("note", "important", "tip", "warning", "caution")

_CALLOUT_MARKER = re.compile(r"^\[!(note|important|tip|warning|caution)\]\s*", re.IGNORECASE)
_ANCHOR_TAG = re.compile(r"""<a\s[^>]*?\b(?:name|id)\s*=\s*["']([^"']+)["']""", re.IGNORECASE)
_FRONT_MATTER = re.compile(r"\A---[ \t]*\r?\n.*?\r?\n---[ \t]*(?:\r?\n|\Z)", re.DOTALL)
_SCHEME = re.compile(r"^[a-z][a-z0-9+.-]*:", re.IGNORECASE)
_LOCALE_PREFIX = re.compile(r"^/[a-z]{2}-[a-z]{2}/", re.IGNORECASE)
_WHITESPACE = re.compile(r"\s+")
_RUN_FLAGS = ("strong", "em", "code")

Resolver = Callable[[str], str | None]
Run = dict[str, Any]


def collapse(text: str) -> str:
    return _WHITESPACE.sub(" ", text).strip()


def strip_front_matter(markdown: str) -> str:
    return _FRONT_MATTER.sub("", markdown, count=1)


def parse_tokens(markdown: str) -> list[Token]:
    """Parse article Markdown (without YAML front matter) into markdown-it block tokens."""
    parser = MarkdownIt("commonmark", {"html": True}).enable(["table", "strikethrough"])
    return parser.parse(strip_front_matter(markdown))


def _children(token: Token | None) -> list[Token]:
    if token is None or not token.children:
        return []
    return list(token.children)


def inline_lines(token: Token | None) -> list[str]:
    """Plain text of an inline token split at source line breaks; empty lines are dropped."""
    lines = [""]
    for child in _children(token):
        if child.type in ("softbreak", "hardbreak"):
            lines.append("")
        elif child.type in ("text", "code_inline"):
            lines[-1] += child.content
    return [text for text in (collapse(line) for line in lines) if text]


def inline_text(token: Token | None) -> str:
    """Plain text of an inline token with whitespace collapsed (HTML and images omitted)."""
    return " ".join(inline_lines(token))


def heading_text_raw(token: Token | None) -> str:
    """Heading text as Markdig sees it for identifiers: whitespace kept, ends trimmed."""
    parts: list[str] = []
    for child in _children(token):
        if child.type in ("text", "code_inline"):
            parts.append(child.content)
        elif child.type in ("softbreak", "hardbreak"):
            parts.append(" ")
    return "".join(parts).strip()


def explicit_anchors(token: Token | None) -> list[str]:
    """Anchor names declared with inline HTML such as ``<a name="windows"></a>``."""
    names: list[str] = []
    for child in _children(token):
        if child.type == "html_inline":
            names.extend(name.strip() for name in _ANCHOR_TAG.findall(child.content))
    return [name for name in names if name]


def slugify(text: str) -> str:
    """GitHub-style heading identifier, as generated by Markdig for Microsoft Learn.

    Letters, decimal digits, hyphens, and underscores are kept (lowercased); spaces become
    hyphens; everything else is removed.
    """
    chars: list[str] = []
    for char in text.strip():
        if char.isalpha() or char.isdecimal() or char in "-_":
            chars.append(char.lower())
        elif char == " ":
            chars.append("-")
    return "".join(chars)


@dataclass
class SlugRegistry:
    """Unique identifiers within one article; duplicates get -1, -2, ... like Markdig."""

    used: set[str] = field(default_factory=set)

    def reserve(self, slug: str) -> None:
        self.used.add(slug)

    def unique(self, text: str) -> str:
        base = slugify(text) or "section"
        slug = base
        counter = 0
        while slug in self.used:
            counter += 1
            slug = f"{base}-{counter}"
        self.used.add(slug)
        return slug


def link_resolver(file_path: str, article_url: str) -> Resolver:
    """Resolve links in ``file_path`` (a repository path under ``articles/``) to https URLs.

    Repository-relative ``.md`` links map to Microsoft Learn article URLs, root-relative links map
    to ``learn.microsoft.com/en-us``, absolute https links are kept, and anything else (http,
    mailto, script schemes, media files, paths outside ``articles/``) resolves to ``None``.
    """
    directory = posixpath.dirname(file_path)

    def resolve(href: str) -> str | None:
        target = href.strip()
        if not target:
            return None
        if target.lower().startswith("https://"):
            return target
        if target.startswith("//") or _SCHEME.match(target):
            return None
        path, hash_mark, anchor = target.partition("#")
        path, question, query = path.partition("?")
        if not path:
            url = article_url
        elif path.startswith("/"):
            url = LEARN_LOCALE_BASE + _LOCALE_PREFIX.sub("/", path).lstrip("/")
        else:
            joined = posixpath.normpath(posixpath.join(directory, path))
            if not joined.startswith(ARTICLES_ROOT) or not joined.endswith(".md"):
                return None
            url = DYNAMICS_BASE + joined[len(ARTICLES_ROOT) : -len(".md")]
        if question and query:
            url = f"{url}?{query}"
        if hash_mark and anchor:
            url = f"{url}#{anchor}"
        return url

    return resolve


def _flags(run: Run) -> tuple[Any, ...]:
    return (*(run.get(flag) for flag in _RUN_FLAGS), run.get("href"))


def make_run(
    text: str,
    *,
    strong: bool = False,
    em: bool = False,
    code: bool = False,
    href: str | None = None,
) -> Run:
    run: Run = {"text": text}
    if strong:
        run["strong"] = True
    if em:
        run["em"] = True
    if code:
        run["code"] = True
    if href:
        run["href"] = href
    return run


def trim_runs(runs: list[Run]) -> list[Run]:
    """Trim outer whitespace, then drop empty runs."""
    result = [dict(run) for run in runs]
    while result and not result[0]["text"].strip():
        result.pop(0)
    while result and not result[-1]["text"].strip():
        result.pop()
    if result:
        result[0]["text"] = result[0]["text"].lstrip()
        result[-1]["text"] = result[-1]["text"].rstrip()
    return [run for run in result if run["text"]]


def inline_runs(token: Token | None, resolve: Resolver) -> list[Run]:
    """Formatted text runs of an inline token. Links keep only resolved https targets."""
    runs: list[Run] = []
    strong = 0
    em = 0
    links: list[str | None] = []

    def emit(text: str, *, code: bool = False) -> None:
        value = _WHITESPACE.sub(" ", text)
        if not value:
            return
        run = make_run(
            value,
            strong=strong > 0,
            em=em > 0,
            code=code,
            href=links[-1] if links else None,
        )
        if runs and runs[-1]["text"].endswith(" ") and value.startswith(" "):
            value = value[1:]
            if not value:
                return
            run["text"] = value
        if runs and _flags(runs[-1]) == _flags(run):
            runs[-1]["text"] += value
        else:
            runs.append(run)

    for child in _children(token):
        kind = child.type
        if kind == "text":
            emit(child.content)
        elif kind == "code_inline":
            emit(child.content, code=True)
        elif kind in ("softbreak", "hardbreak"):
            emit(" ")
        elif kind == "strong_open":
            strong += 1
        elif kind == "strong_close":
            strong = max(0, strong - 1)
        elif kind == "em_open":
            em += 1
        elif kind == "em_close":
            em = max(0, em - 1)
        elif kind == "link_open":
            links.append(resolve(str(child.attrGet("href") or "")))
        elif kind == "link_close" and links:
            links.pop()
    return trim_runs(runs)


def runs_text(runs: Sequence[Run]) -> str:
    return collapse("".join(run["text"] for run in runs))


def split_callout(runs: list[Run]) -> tuple[str | None, list[Run]]:
    """Detect a DocFX callout marker (``[!NOTE]``) at the start of a paragraph's runs."""
    if not runs or runs[0].get("href") or runs[0].get("code"):
        return None, runs
    match = _CALLOUT_MARKER.match(runs[0]["text"])
    if not match:
        return None, runs
    rest = runs[0]["text"][match.end() :]
    remaining = ([{**runs[0], "text": rest}] if rest else []) + runs[1:]
    return match.group(1).lower(), trim_runs(remaining)


@dataclass
class Node:
    """Block-level Markdown node (headings, paragraphs, lists, quotes, tables)."""

    kind: str
    level: int = 0
    inline: Token | None = None
    ordered: bool = False
    start: int = 1
    rows: list[list[Token | None]] = field(default_factory=list)
    children: list[Node] = field(default_factory=list)


def table_cells(tokens: Sequence[Token], start: int) -> tuple[list[list[Token | None]], int]:
    """Inline token per cell for the table opening at ``tokens[start]``; header row first."""
    rows: list[list[Token | None]] = []
    current: list[Token | None] = []
    cell: Token | None = None
    in_cell = False
    index = start + 1
    while index < len(tokens):
        token = tokens[index]
        if token.type == "table_close":
            return rows, index + 1
        if token.type == "tr_open":
            current = []
        elif token.type in ("th_open", "td_open"):
            in_cell = True
            cell = None
        elif token.type == "inline" and in_cell:
            cell = token
        elif token.type in ("th_close", "td_close"):
            current.append(cell)
            in_cell = False
        elif token.type == "tr_close":
            rows.append(current)
        index += 1
    raise ParserError("Markdown table was not closed")


def table_text_rows(tokens: Sequence[Token], start: int) -> tuple[tuple[tuple[str, ...], ...], int]:
    rows, index = table_cells(tokens, start)
    return tuple(tuple(inline_text(cell) for cell in row) for row in rows), index


def header_key(cells: Sequence[str]) -> tuple[str, ...]:
    return tuple(collapse(cell).casefold() for cell in cells)


def find_table(markdown: str, headers: Sequence[str]) -> tuple[tuple[str, ...], ...] | None:
    """Rows of the first table whose header row matches ``headers``, ignoring case and spacing."""
    tokens = parse_tokens(markdown)
    expected = header_key(headers)
    index = 0
    while index < len(tokens):
        if tokens[index].type == "table_open":
            rows, index = table_text_rows(tokens, index)
            if rows and header_key(rows[0]) == expected:
                return rows
            continue
        index += 1
    return None


def block_tree(tokens: Sequence[Token]) -> list[Node]:
    """Nest markdown-it block tokens into a tree of :class:`Node` objects."""
    root = Node("root")
    stack = [root]
    index = 0
    closers = {"bullet_list_close", "ordered_list_close", "list_item_close", "blockquote_close"}
    while index < len(tokens):
        token = tokens[index]
        kind = token.type
        parent = stack[-1]
        if kind in ("heading_open", "paragraph_open"):
            inline = tokens[index + 1] if index + 1 < len(tokens) else None
            if kind == "heading_open":
                parent.children.append(Node("heading", level=int(token.tag[1:]), inline=inline))
            else:
                parent.children.append(Node("paragraph", inline=inline))
            index += 3
            continue
        if kind == "table_open":
            rows, index = table_cells(tokens, index)
            parent.children.append(Node("table", rows=rows))
            continue
        if kind in ("bullet_list_open", "ordered_list_open"):
            start_attr = token.attrGet("start")
            node = Node(
                "list",
                ordered=kind == "ordered_list_open",
                start=int(start_attr) if start_attr is not None else 1,
            )
            parent.children.append(node)
            stack.append(node)
        elif kind in ("list_item_open", "blockquote_open"):
            node = Node("item" if kind == "list_item_open" else "blockquote")
            parent.children.append(node)
            stack.append(node)
        elif kind in closers:
            if len(stack) > 1:
                stack.pop()
        elif kind in ("fence", "code_block", "html_block", "hr"):
            parent.children.append(Node(kind))
        index += 1
    return root.children
